import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Providers from './providers';
import ConditionalLayout from '@/components/ConditionalLayout/ConditionalLayout';

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Гранит памяти",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body style={{ margin: 0, padding: 0, overflow: 'visible' }}>
        <Providers>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </Providers>
      </body>
    </html>
  );
}
